# General Aliases
alias df='df -h'
alias la='ls -la'
alias ll='ls -alF'

# Use neovim over vim
alias vim='nvim'

# Git Aliases
alias gs='git status'
alias gpoh='git push origin HEAD'
alias gcm='git commit -m'
alias gb='git branch'
__git_complete gb _git_branch # Enable autocompletion for alias
alias gc='git checkout'
__git_complete gc _git_checkout # Enable autocompletion for alias

# Docker Aliases
alias dimg='docker images'
alias dps='docker ps -a'

# Sweeter Neo
alias neo='neofetch'

# RICE Config Editing Aliases
alias polycfg='vim /home/ryan/.config/polybar/config'
alias i3cfg='vim /home/ryan/.config/i3/config'
alias xres='vim /home/ryan/.Xresources'
alias vimrc='vim /home/ryan/.config/nvim/init.vim'

# Screenshot Alias
alias ss='maim -s /home/ryan/Pictures/screenshot.png'

# Fuzzyfind -> Vim Alias
alias ff='vim $(fzf)'

# Nice Git Diff -> Fzf function
fd()
{
  if [ -d .git ]; then
    preview="git diff $@ --color=always -- {-1}"
    git diff $@ --name-only | fzf -m --ansi --preview "$preview"
  else
    echo "Error: Either not a git repository or not at the root of the project"
  fi;
}
